# Generated by Django 2.1.1 on 2018-09-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(max_length=500)),
                ('name', models.CharField(default='Unnamed Item', max_length=500)),
            ],
        ),
    ]
