# Generated by Django 2.0.5 on 2018-09-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image_url',
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(null=True, upload_to='order_images/'),
        ),
    ]
